version: '3.8'

services:
  laravel-app:
    build:
      context: "."
      args:
        uid: ${UID}
    container_name: laravel-app
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
      - MONGODB_HOST=mongodb
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    networks:
      backend:
        aliases:
          - app

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      backend:
        aliases:
          - redis-cache-db

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - mongo-db

volumes:
  mongo-data:

networks:
  backend:
    name: backend-network
