name: App Deployment
run-name: ${{ github.actor }} is deploying the application
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  app-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.x'

      - name: Build and run Docker container
        run: |
          docker compose up --build -d
          docker compose exec -T laravel-app sh -c "php artisan key:generate && php artisan migrate"
      
      - name: Run PHP Unit testing
        run: |
          docker compose exec -T laravel-app sh -c "./vendor/bin/phpunit --verbose tests"

