name: App Building and Testing
run-name: ${{ github.actor }} is testing the application
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  app-setup:
    runs-on: ubuntu-latest
    env:
      UID: 1000 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Build and run Docker container
        run: |
          cp .env.example .env
          composer install
          docker compose up --build -d
      - name: Await for mongo and redis to start
        run: |
          sleep 60
      - name: Check MongoDB container logs
        run: |
          docker compose exec -T businessmanagement-mongo-1 sh -c "mongo --eval 'db.serverStatus()'"
      - name: Set key run migrations
        run: |
          docker compose exec -T laravel-app sh -c "php artisan key:generate && php artisan migrate"
      
      - name: Run PHP Unit testing
        run: |
          docker compose exec -T laravel-app sh -c "./vendor/bin/phpunit --verbose tests"

