name: App Deployment
run-name: ${{ github.actor }} is deploying the application
on:
  push: 
    branches: [main]
jobs:
  app-setup:
    runs-on: ubuntu-latest
    steps:
      - run: docker compose up --build
      - run: docker exec -it laravel-app sh
      - run: php artisan key:generate
      - run: php artisan migrate
      - run: exit
